### ISSUE TITLE
[Importer] Update the Products import to provide/create a list resource that is used by OpenSRP clients to fetch products

### ISSUE THREAD

**Issue by dubdabasoduba** [onaio/fhir-tooling#217]
## Context
- The OpenSRP web and mobile app use a List of resources to load the Group resources representing the product. 
- This list resource stores the Group and Binary resources representing the Product and its image. 
- The web allows [list reference](https://github.com/onaio/fhir-web/blob/f8787469b5f0a931888b0dd940887a71542d142a/app/.env.sample#L45) in the following `.env`.  
    - If the `.env` is not blank then we use that LIST
    - If the `.env` is blank we then create the LIST

 ## Implementation
- [ ] Update the tooling to add the Groups and Binary resources to the inventory List

**Comment by Wambere** [comment]
@dubdabasoduba I need a bit more information on this
The task is to create/update a list resource with all the products (Group resources) that are imported?

**Comment by Mstjamush** [comment]
**Issues**

1. Location upload - Upload shows to be successful but location is available on Web
2. Organization-Location assignment is not happening (Could be because of Location upload issue)
3. Product upload is failing. (reference the screen shot attached)

![Image](https://github.com/user-attachments/assets/56ef9e0b-5a67-4d1a-bccc-f3d8b29f91bf)
